//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlug.Ext.MPLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlug.Ext.MPLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32px {
            get {
                object obj = ResourceManager.GetObject("_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* scripts\bootstrap-2.3.2\bootstrap-transition.js */
        ///        ////* ===================================================
        /// * bootstrap-transition.js v2.3.2
        /// * http://twitter.github.com/bootstrap/javascript.html#transitions
        /// * ===================================================
        /// * Copyright 2012 Twitter, Inc.
        /// *
        /// * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        /// * you may not use this file except in compliance with the License.
        /// * You may obtain a copy of the License at
        /// *
        /// * http://www.apache.org/licen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_js {
            get {
                return ResourceManager.GetString("bootstrap_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function(a){a(function(){a.support.transition=(function(){var b=(function(){var e=document.createElement(&quot;bootstrap&quot;),d={WebkitTransition:&quot;webkitTransitionEnd&quot;,MozTransition:&quot;transitionend&quot;,OTransition:&quot;oTransitionEnd otransitionend&quot;,transition:&quot;transitionend&quot;},c;for(c in d){if(e.style[c]!==undefined){return d[c]}}}());return b&amp;&amp;{end:b}})()})}(window.jQuery);!function(d){var c=&apos;[data-dismiss=&quot;alert&quot;]&apos;,b=function(e){d(e).on(&quot;click&quot;,c,this.close)};b.prototype.close=function(j){var i=d(this),g=i.attr(&quot;data-ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min {
            get {
                return ResourceManager.GetString("bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio,canvas,video{display:inline-block;*display:inline;*zoom:1}audio:not([controls]){display:none}html{font-size:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}a:focus{outline:thin dotted #333;outline:5px auto -webkit-focus-ring-color;outline-offset:-2px}a:hover,a:active{outline:0}sub,sup{position:relative;font-size:75%;line-height:0;vertical-align:baseline}sup{top:-0.5em}sub{bottom:-0.25em}img{max-width:10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min_css {
            get {
                return ResourceManager.GetString("bootstrap_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///&lt;div id=&quot;mp-modal-eventselect&quot; class=&quot;mp-modal&quot;&gt;
        ///    &lt;div class=&quot;mp-modal-dialog modal-dialog-centered&quot;&gt;
        ///        &lt;div class=&quot;mp-modal-content&quot;&gt;
        ///            &lt;div class=&quot;mp-modal-header&quot;&gt;
        ///                &lt;div class=&quot;title-icon&quot;&gt;
        ///                    &lt;h5 class=&quot;mp-modal-title&quot;&gt;MultiPlug Events&lt;/h5&gt;
        ///                &lt;/div&gt;
        ///                &lt;button type=&quot;button&quot; class=&quot;close mp-modal-btn-close&quot;&gt;
        ///                    &lt;span&gt;×&lt;/span&gt;
        ///                &lt;/button&gt;
        ///            &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventPicker_html {
            get {
                return ResourceManager.GetString("EventPicker_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function applyMPEventPickerOnClick() {
        ///    $(&quot;.mp-event-picker&quot;).click(function () {
        ///
        ///        var TheValueToUpdate = $(this);
        ///
        ///        $.get(&quot;apps/multiplug.ext.mplib/event-picker/&quot;, function (data, status) {
        ///            $(&apos;body&apos;).append(&apos;&lt;div id=&quot;mp-modal-eventselectbackdrop&quot; class=&quot;mp-modal-backdrop fade show&quot;&gt;&lt;/div&gt;&apos;);
        ///            $(&apos;body&apos;).prepend(data);
        ///
        ///            $(&quot;#mp-modal-eventselectvalue&quot;).change(function () {
        ///                $(&quot;#mp-modal-eventid-input&quot;).val($(this).val());
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eventpicker_js {
            get {
                return ResourceManager.GetString("eventpicker_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.10.2
        /// * http://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// *
        /// * Copyright 2005, 2013 jQuery Foundation, Inc. and other contributors
        /// * Released under the MIT license
        /// * http://jquery.org/license
        /// *
        /// * Date: 2013-07-03T13:48Z
        /// */
        ///(function( window, undefined ) {
        ///
        ///// Can&apos;t do this because several apps including ASP.NET trace
        ///// the stack via arguments.caller.callee and Firefox dies if
        ///// you try to trace through &quot;use strict&quot; call chains. ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_10_2_js {
            get {
                return ResourceManager.GetString("jquery_1_10_2_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v3.2.1
        /// * https://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * https://sizzlejs.com/
        /// *
        /// * Copyright JS Foundation and other contributors
        /// * Released under the MIT license
        /// * https://jquery.org/license
        /// *
        /// * Date: 2017-03-20T18:59Z
        /// */
        ///( function( global, factory ) {
        ///
        ///	&quot;use strict&quot;;
        ///
        ///	if ( typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot; ) {
        ///
        ///		// For CommonJS and CommonJS-like environments where a proper `window`
        ///		// is present, execute the f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_3_2_1 {
            get {
                return ResourceManager.GetString("jquery_3_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v3.2.1 | (c) JS Foundation and other contributors | jquery.org/license */
        ///!function(a,b){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){&quot;use strict&quot;;var c=[],d=a.document,e=Object.getPrototypeOf,f=c.slice,g=c.concat,h=c.push,i=c.indexOf,j={},k=j.toString,l=j.hasOwnProperty,m=l.toStri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_3_2_1_min {
            get {
                return ResourceManager.GetString("jquery_3_2_1_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * ASP.NET SignalR JavaScript Library 2.4.3
        /// * http://signalr.net/
        /// *
        /// * Copyright (c) .NET Foundation. All rights reserved.
        /// * Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
        /// *
        /// */
        ///(function(n,t,i){function w(t,i){var u,f;if(n.isArray(t)){for(u=t.length-1;u&gt;=0;u--)f=t[u],n.type(f)===&quot;string&quot;&amp;&amp;r.transports[f]||(i.log(&quot;Invalid transport: &quot;+f+&quot;, removing it from the transports list.&quot;),t.splice(u,1));t.length===0&amp;&amp;(i.log(&quot;No transports remain wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_signalR_2_4_3_min {
            get {
                return ResourceManager.GetString("jquery_signalR_2_4_3_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jsTree - v3.3.3 - 2016-10-31 - (MIT) */
        ///!function(a){&quot;use strict&quot;;&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],a):&quot;undefined&quot;!=typeof module&amp;&amp;module.exports?module.exports=a(require(&quot;jquery&quot;)):a(jQuery)}(function(a,b){&quot;use strict&quot;;if(!a.jstree){var c=0,d=!1,e=!1,f=!1,g=[],h=a(&quot;script:last&quot;).attr(&quot;src&quot;),i=window.document;a.jstree={version:&quot;3.3.3&quot;,defaults:{plugins:[]},plugins:{},path:h&amp;&amp;-1!==h.indexOf(&quot;/&quot;)?h.replace(/\/[^\/]+$/,&quot;&quot;):&quot;&quot;,idregex:/[\\:&amp;!^|()\[\]&lt;&gt;@*&apos;+~#&quot;;.,=\- \/${}%?`]/g,root:&quot;# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jstree_min_js {
            get {
                return ResourceManager.GetString("jstree_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jstree-node,.jstree-children,.jstree-container-ul{display:block;margin:0;padding:0;list-style-type:none;list-style-image:none}.jstree-node{white-space:nowrap}.jstree-anchor{display:inline-block;color:#000;white-space:nowrap;padding:0 4px 0 1px;margin:0;vertical-align:top}.jstree-anchor:focus{outline:0}.jstree-anchor,.jstree-anchor:link,.jstree-anchor:visited,.jstree-anchor:hover,.jstree-anchor:active{text-decoration:none;color:inherit}.jstree-icon{display:inline-block;text-decoration:none;margin:0;padding: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jstree_style_min_css {
            get {
                return ResourceManager.GetString("jstree_style_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function ($, window) {
        ///
        ///    $.multiplug = {
        ///        // subscribedEvent : new Event(&apos;onMultiPlugViewSubscribed&apos;)
        ///    };
        ///
        ///    $.connection.hub.url = &quot;stream&quot;;
        ///    var hub = $.connection.wS;
        ///
        ///    $.connection.hub.error(function (error) {
        ///        console.log(&apos;Web Socket Error: &apos; + error);
        ///    });
        ///
        ///    $.connection.hub.logging = true;
        ///
        ///    $.connection.wS.client.send = function (id, Payload) {
        ///        // Required to trigger On(Dis)Connected to fire.
        ///    };
        ///
        ///    $.connection.wS.client.forceref [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string multiplugpart1_js {
            get {
                return ResourceManager.GetString("multiplugpart1_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;;
        ///
        ///        if( ResponseId == null || ResponseId == &quot;&quot;)
        ///        {
        ///            return;
        ///        }
        ///
        ///        hub.server.subscribe( ResponseId );
        ///
        ///        // $(document).trigger(&quot;multiplugReady&quot;);
        ///
        ///        var event = new CustomEvent(&quot;multiplugReady&quot;, {
        ///        });
        ///
        ///        window.dispatchEvent(event);
        ///
        ///    });
        ///
        ///}(window.jQuery, window));.
        /// </summary>
        internal static string multiplugpart2_js {
            get {
                return ResourceManager.GetString("multiplugpart2_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssdp_png {
            get {
                object obj = ResourceManager.GetObject("ssdp_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap throbber {
            get {
                object obj = ResourceManager.GetObject("throbber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
